---
address:
  localhost:8080

vapi_host:
  https://api.nexmo.com

bearer_token:
  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NDI2NTAyOTksImp0aSI6InlWSElqNGh0S3JfWFlWRDFpNVdXakdkakM5ZW10NW5pRGVkTlRqWDJXcXlLUk5CSVBScHVMXzU1T3pVT0daRWFqT0FGZ0g3TjNyMnJ0ZFdZM3ltRkV3PT0iLCJhcHBsaWNhdGlvbl9pZCI6IjA4YjcyN2MwLTZmODItNGYyMy1hMTllLTIzZWJhYzU4ZGE0OCIsImV4cCI6MTU0NTI0MjMwMn0.O6D9Z55aQnEaNKilc6IR-XVHSKNUY6g_VH3ImhSTz0thnP33ApdT2OsmDnUJhyBsYjVq3WDM9xOmcxkrhpx3k6yWo5vbWPvc91n2PTHyWx91q3gm4oslMlwWT5mupp7kMUNTOQ2oUu-WVjF0CH1aeD6a66bIG_yV4t6o60knnk5sItckwGWNF0XbjDnSOjhQHDtA4JYMW3ijC8RqxbX-P6KGgyHdTOCT8GWudDn3Dtqy_6S-RSZIhFPFBMGgETcoOpLk4tVNU-HaGi4TO6Tin3JLb1Exk6CRW2FeE3r1bpd35h6nmaCJZ0I7VyxvYjLgffdVbxkP7BOU8B1CH600rw

public:
  /home/demo/public

templates:
  /home/demo/templates

destination_number:
  447429541456

source_number:
  447429541456

call_event_url:
  54.153.132.37:80/callback

answer_url:
  54.153.132.37:80/ncco

ncco_event_url:
  54.153.132.37:80/callback


